//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IUserInfoService")]
public interface IUserInfoService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserInfoService/GetUsersCount", ReplyAction = "http://tempuri.org/IUserInfoService/GetUsersCountResponse")]
    int GetUsersCount();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserInfoService/GetUsersCount", ReplyAction = "http://tempuri.org/IUserInfoService/GetUsersCountResponse")]
    System.Threading.Tasks.Task<int> GetUsersCountAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserInfoService/GetUserTestsCount", ReplyAction = "http://tempuri.org/IUserInfoService/GetUserTestsCountResponse")]
    int GetUserTestsCount(string user);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserInfoService/GetUserTestsCount", ReplyAction = "http://tempuri.org/IUserInfoService/GetUserTestsCountResponse")]
    System.Threading.Tasks.Task<int> GetUserTestsCountAsync(string user);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserInfoServiceChannel : IUserInfoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserInfoServiceClient : System.ServiceModel.ClientBase<IUserInfoService>, IUserInfoService
{

    public UserInfoServiceClient()
    {
    }

    public UserInfoServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public UserInfoServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UserInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UserInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public int GetUsersCount()
    {
        return base.Channel.GetUsersCount();
    }

    public System.Threading.Tasks.Task<int> GetUsersCountAsync()
    {
        return base.Channel.GetUsersCountAsync();
    }

    public int GetUserTestsCount(string user)
    {
        return base.Channel.GetUserTestsCount(user);
    }

    public System.Threading.Tasks.Task<int> GetUserTestsCountAsync(string user)
    {
        return base.Channel.GetUserTestsCountAsync(user);
    }
}
